  
langauge: ruby
rvm:
  - 2.6.5
env:
  'ENV=ci'
cache: bundler
services:
  - postgresql
before_install:
  - gem update --system
  - bundle install
  - rake db:create
  - rake db:migrate
script:
  - rubocop app/*
  - rspec spec